version: '3.8'

services:
  statis:
    image: qih14/uas_2388010016:latest # Menggunakan image dari Docker Hub
    container_name: eperpus_statis
    ports:
      - "80:80" # Memetakan port 80 EC2 ke port 80 Container (web statis)
    restart: always

  dinamis:
    image: qih14/uas_dinamis_2388010016:latest # Menggunakan image dari Docker Hub
    container_name: eperpus_dinamis
    ports:
      - "3000:80" # Memetakan port 3000 EC2 ke port 80 Container (web dinamis PHP Apache)
    # Volumes dinonaktifkan di production agar tidak meng-override code aplikasi dengan folder kosong di host EC2
    # volumes:
    #   - ./web-dinamis:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=perpustakaan
      - DB_USER=root
      - DB_PASSWORD=Rahasia123! # Gunakan password yang kuat untuk AWS
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:10.6 # Menggunakan MariaDB sesuai kriteria penilaian UAS
    container_name: eperpus_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=adminsecretpassword
      - MYSQL_DATABASE=perpustakaan
    # Port 3306 ditutup/tidak diekspos ke publik demi keamanan dan penilaian "Sangat Baik" di UAS
    volumes:
      - db_data:/var/lib/mysql
      # Otomatis mengimport database.sql saat kontainer db pertama kali dibuat
      # File database.sql disalin ke EC2 melalui SCP di GitHub Actions
      - ./web-dinamis/database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  db_data:

